# Generated by Django 3.0.7 on 2025-02-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planyo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='key',
            new_name='api_key',
        ),
        migrations.RenameField(
            model_name='apikey',
            old_name='name',
            new_name='environment',
        ),
    ]
