# Generated by Django 3.0.7 on 2020-11-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('birth_date', models.CharField(max_length=255)),
                ('nin', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_id', models.CharField(max_length=100)),
                ('zl_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('duration_minutes', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.Patient')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.Doctor')),
            ],
        ),
    ]
