# Generated by Django 3.0.7 on 2020-12-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZlFacility',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ZlDoctor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlFacility')),
            ],
        ),
        migrations.CreateModel(
            name='ZlAddress',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlDoctor')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlDoctor'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
