# Generated by Django 3.0.7 on 2020-12-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer', '0002_auto_20201220_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zladdress',
            name='post_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zladdress',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
