# Generated by Django 3.0.7 on 2020-12-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer', '0003_auto_20201220_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZlBooking',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('booked_by', models.CharField(max_length=255)),
                ('canceled_by', models.CharField(max_length=255, null=True)),
                ('booked_at', models.DateTimeField()),
                ('canceled_at', models.CharField(max_length=255, null=True)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('insurance', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
