# Generated by Django 3.0.7 on 2020-12-20 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer', '0004_auto_20201220_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='zlbooking',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlAddress'),
            preserve_default=False,
        ),
    ]
