# Generated by Django 3.0.7 on 2020-12-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer', '0005_zlbooking_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlReservation',
            fields=[
                ('reservation_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('resource_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('cart_id', models.CharField(max_length=255, null=True)),
                ('creation_time', models.DateTimeField()),
                ('unit_assignment', models.CharField(max_length=255, null=True)),
                ('quantity', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user_notes', models.CharField(max_length=255, null=True)),
                ('admin_notes', models.CharField(max_length=255, null=True)),
                ('custom_color', models.CharField(max_length=255, null=True)),
                ('night_reservation', models.CharField(max_length=255, null=True)),
                ('currency', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255, null=True)),
                ('user_id', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=255, null=True)),
                ('mobile_country_code', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('phone_country_code', models.CharField(max_length=255, null=True)),
                ('zip', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('ppp_rs', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
