# Generated by Django 3.0.7 on 2021-01-15 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer', '0007_auto_20201230_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='zl_address_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='zl_doctor_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='zl_facility_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='zl_address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlAddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='zl_doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlDoctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='zl_facility',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlFacility'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
