# Generated by Django 3.0.7 on 2021-01-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer', '0008_auto_20210115_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZlService',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255, null=True)),
                ('is_price_from', models.CharField(max_length=255, null=True)),
                ('service_id', models.CharField(max_length=255, null=True)),
                ('is_default', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=2040, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='zl_service_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
