# Generated by Django 3.0.7 on 2021-01-22 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('birth_date', models.CharField(max_length=255)),
                ('nin', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlReservation',
            fields=[
                ('reservation_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('resource_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('cart_id', models.CharField(max_length=255, null=True)),
                ('creation_time', models.DateTimeField()),
                ('unit_assignment', models.CharField(max_length=255, null=True)),
                ('quantity', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user_notes', models.CharField(max_length=255, null=True)),
                ('admin_notes', models.CharField(max_length=255, null=True)),
                ('custom_color', models.CharField(max_length=255, null=True)),
                ('night_reservation', models.CharField(max_length=255, null=True)),
                ('currency', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255, null=True)),
                ('user_id', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=255, null=True)),
                ('mobile_country_code', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('phone_country_code', models.CharField(max_length=255, null=True)),
                ('zip', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('ppp_rs', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZlAddress',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZlAddressService',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255, null=True)),
                ('is_price_from', models.CharField(max_length=255, null=True)),
                ('is_default', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=2040, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZlFacility',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ZlService',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ZlSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlAddress')),
            ],
        ),
        migrations.CreateModel(
            name='ZlDoctor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlFacility')),
            ],
        ),
        migrations.CreateModel(
            name='ZlBooking',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('booked_by', models.CharField(max_length=255)),
                ('canceled_by', models.CharField(max_length=255, null=True)),
                ('booked_at', models.DateTimeField()),
                ('canceled_at', models.CharField(max_length=255, null=True)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('insurance', models.CharField(max_length=255, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlAddress')),
                ('address_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlAddressService')),
            ],
        ),
        migrations.AddField(
            model_name='zladdressservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlService'),
        ),
        migrations.AddField(
            model_name='zladdress',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlDoctor'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_reservation_id', models.CharField(max_length=255, null=True)),
                ('pl_resource_id', models.CharField(max_length=255, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('email', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('zl_resource_id', models.CharField(max_length=255, null=True)),
                ('zl_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlAddress')),
                ('zl_address_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlAddressService')),
                ('zl_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlDoctor')),
                ('zl_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlFacility')),
                ('zl_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.ZlSlot')),
            ],
        ),
    ]
