# Generated by Django 5.1.6 on 2025-02-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('birth_date', models.CharField(max_length=255)),
                ('nin', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlReservation',
            fields=[
                ('reservation_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('resource_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('cart_id', models.CharField(max_length=255, null=True)),
                ('creation_time', models.DateTimeField()),
                ('unit_assignment', models.CharField(max_length=255, null=True)),
                ('quantity', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user_notes', models.CharField(max_length=255, null=True)),
                ('admin_notes', models.CharField(max_length=255, null=True)),
                ('custom_color', models.CharField(max_length=255, null=True)),
                ('night_reservation', models.CharField(max_length=255, null=True)),
                ('currency', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255, null=True)),
                ('user_id', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=255, null=True)),
                ('mobile_country_code', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('phone_country_code', models.CharField(max_length=255, null=True)),
                ('zip', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('ppp_rs', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlResource',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ZlAddress',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZlDoctor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ZlFacility',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ZlService',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ZlAddressService',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255, null=True)),
                ('is_price_from', models.CharField(max_length=255, null=True)),
                ('service_id', models.CharField(max_length=255, null=True)),
                ('is_default', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=2040, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.zladdress')),
            ],
        ),
        migrations.CreateModel(
            name='ZlBooking',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('booked_by', models.CharField(max_length=255)),
                ('canceled_by', models.CharField(max_length=255, null=True)),
                ('booked_at', models.DateTimeField()),
                ('canceled_at', models.CharField(max_length=255, null=True)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('insurance', models.CharField(max_length=255, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.zladdress')),
                ('address_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.zladdressservice')),
            ],
        ),
        migrations.AddField(
            model_name='zladdress',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.zldoctor'),
        ),
        migrations.AddField(
            model_name='zldoctor',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.zlfacility'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_reservation_id', models.CharField(max_length=255, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('email', models.CharField(default='empty@example.com', max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('zl_resource_id', models.CharField(max_length=255, null=True)),
                ('pl_resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.plresource')),
                ('zl_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.zladdress')),
                ('zl_address_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.zladdressservice')),
                ('zl_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.zldoctor')),
                ('zl_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synchronizer.zlfacility')),
            ],
        ),
    ]
